#!/usr/bin/php -q
<?php

include dirname(__FILE__) . '/vendor/autoload.php';
include dirname(__FILE__) . '/App/config.php';

// Generator Classes
include dirname(__FILE__) . '/Framework/Generator/WPGenarator.php';
include dirname(__FILE__) . '/Framework/Generator/Functions/Map.php';
include dirname(__FILE__) . '/Framework/Generator/Functions/Make.php';
include dirname(__FILE__) . '/Framework/Generator/Functions/Listing.php';

// Database Classes
use DB\WPDataTable;
use DB\WPBlueprint;


WPGenarator::cmd('make', 'controller', 'business', [])->run();




